REGISTER QUERY q08 AS
PREFIX ns1: <http://kr.tuwien.ac.at/dhsr/>
SELECT (Count (DISTINCT ?stt_id) AS ?C)
FROM STREAM <http://kr.tuwien.ac.at/dhsr/stream> [RANGE 1s STEP 1s]
WHERE {
	?stt_id ns1:hasDelay ?del.
	}

