REGISTER QUERY q05 AS
PREFIX ns1: <http://kr.tuwien.ac.at/dhsr/>
SELECT ?stt_id (?del / 60 AS ?del_min)
FROM STREAM <http://kr.tuwien.ac.at/dhsr/stream> [RANGE 1s STEP 1s]
WHERE {
	?stt_id ns1:hasDelay ?del.
	}

