PREFIX ns1: <http://kr.tuwien.ac.at/dhsr/>
SELECT (Count (?stt_id) AS ?C)
FROM NAMED <http://kr.tuwien.ac.at/dhsr/>
WHERE {
	STREAM <http://kr.tuwien.ac.at/dhsr/stream> [RANGE 4s]
	{?stt_id ns1:hasDelay ?del}
}

